### ISSUE TITLE
required attributes of a definition not validated correctly

### ISSUE THREAD

**Issue by giuliopulina** [sylvainlaurent/swagger-validator-maven-plugin#4]
Hello, 

I noticed that the validator doesn't work well in case of not existing properties defined in 'required' sections.
Let me explain better with an example:
```
Address:
  type: object
  properties:
    name:
      type: string
    surname:
      type: string
    addressLine:
      type: string
  required:
    - not_existing_property
```

This definition passes the validation, and I think it's not correct (swagger editor, in such cases, says: "Missing required property definition: not_existing_property".

Do you know where I can look to fix it? Could it be linked to this issue https://github.com/swagger-api/swagger-parser/issues/452?

Thanks
Giulio
